# backend/Dockerfile.inference
FROM python:3.9-slim-buster

# Укажем рабочую директорию внутри контейнера
WORKDIR /app

# Используем относительные пути из папки backend
COPY ./main_inference.py .
COPY ./requirements.txt .

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Открываем порт 8000 для доступа
EXPOSE 8000

# Указываем команду для запуска приложения
CMD ["uvicorn", "main_inference:app", "--host", "0.0.0.0", "--port", "8000"]
